# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='name',
        ),
        migrations.AddField(
            model_name='gear',
            name='brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='gear',
            name='full_name',
            field=models.CharField(default='blanket', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gear',
            name='model',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='gear',
            name='short_name',
            field=models.CharField(default='blanket', max_length=50),
            preserve_default=False,
        ),
    ]
