# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-01 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170531_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
